"use strict";
exports.__esModule = true;
var classProfessional_1 = require("./classProfessional");
var prof1 = new classProfessional_1.Professional("William Bradley Pitt", 57, "masculino", 1.80, 78, "rubio", "azules", "blanca", false, "estadounidense", 2, "actor y productor");
var prof2 = new classProfessional_1.Professional("George Timothy Clooney", 59, "masculino", 1.78, 80, "cano", "marrones", "blanca", false, "estadounidense", 2, "actor, director, productor y guionista");
var prof3 = new classProfessional_1.Professional("Clinton Eastwood, Jr.", 90, "masculino", 1.93, 75, "cano", "marrones", "blanca", false, "estadounidense", 12, "actor, director, músico y compositor");
var prof4 = new classProfessional_1.Professional("Jennifer Joanna Aniston", 51, "femenino", 1.62, 53, "rubio", "azules", "blanca", false, "estadounidense", 0, "actriz, directora y productora");
var prof5 = new classProfessional_1.Professional("Zoe Yadira Saldaña Nazario", 42, "femenino", 1.65, 69, "negro", "marrones", "afroamericana", false, "estadounidense", 0, "actriz y bailarina");
var prof6 = new classProfessional_1.Professional("Pedro Almodóvar Caballero", 71, "masculino", 1.71, 90, "cano", "marrones", "blanca", false, "española", 2, "director, actor, productor, guionista y cantante");
var prof7 = new classProfessional_1.Professional("Elena Anaya Gutiérrez", 45, "femenino", 1.65, 69, "castaño", "marron castaño y avellana", "blanca", false, "española", 0, "actriz");
var prof8 = new classProfessional_1.Professional("Natalia Gastiain Tena", 36, "femenino", 1.72, 70, "castaño", "verdes", "blanca", false, "británica", 0, "actriz y músico");
var prof9 = new classProfessional_1.Professional("Juan Antonio García Bayona", 45, "masculino", 1.70, 82, "moreno", "marron", "blanca", false, "española", 0, "director");
var prof10 = new classProfessional_1.Professional("Iciar Bollain Pérez-Mínguez", 53, "femenino", 1.55, 59, "pelirrojo", "verdes", "blanca", false, "española", 0, "actriz y directora");
console.log(prof1.professional());
console.log(prof2.professional());
console.log(prof3.professional());
console.log(prof4.professional());
console.log(prof5.professional());
console.log(prof6.professional());
console.log(prof7.professional());
console.log(prof8.professional());
console.log(prof9.professional());
console.log(prof10.professional());
